### ISSUE TITLE
Missing CSS files? Anyway, can't convert SCSS file to CSS

### ISSUE THREAD

**Issue by DavidBevi** [HKayn/vivaldi-vh#6]
Hi, and thanks for making this theme and sharing it!
I'm trying to use [`vivaldi-vh-vivalarc.scss`](https://raw.githubusercontent.com/HKayn/vivaldi-vh/main/vivaldi-vh-vivalarc.scss) by converting it to a **css** file, but I can't find a compiler that does it.

---

 _Edit: I used 10 online compilers. Originally I made a table to list their errors. I then understood that I was converting a file without its imported sources, so I used VSCodium to make the css files below._

| Files for Vivaldi VH | Files for Vivaldi VH Vivalarc |
| -- | -- |
| [vivaldi-vh.css.zip](https://github.com/HKayn/vivaldi-vh/files/14484549/vivaldi-vh.css.zip) | [vivaldi-vh-vivalarc.css.zip](https://github.com/HKayn/vivaldi-vh/files/14484550/vivaldi-vh-vivalarc.css.zip) |

> Files made with [VSCodium](https://vscodium.com) and the extension [scss to css](https://open-vsx.org/extension/oorzc/scss-to-css-compile)

### The idea: the user must provide the compiler all the contents of this repo.
I'm just a novice developer, and I failed to imagine that the SCSS was depending on other files. That's why 10 different online compilers can't compile the code in the SCSS, it's incomplete.

### To dev:
Boy was it hard. A noob like me doesn't have enough clues to get it from your guide, but I'm stubborn, I did a lot of research and eventually found the solution. 

**I think you should update your guide**. I don't understand SASS enough to make coherent suggestions, but I noted it's like a fifth of the code of the CSS so I think people will benefit from an how-to-customize guide. Cheers!

**Comment by DavidBevi** [comment]
I also used [scss to css extension](https://open-vsx.org/extension/oorzc/scss-to-css-compile) in VSCodium:

```
2024-03-04 16:11:17.771 [error] 编译错误 Can't find stylesheet to import.
   ╷
13 │ @use "base";
   │ ^^^^^^^^^^^
   ╵
  c:\Users\utente\AppData\Local\Vivaldi\Mods\VivalArc-main\css\vivaldi-vh-vivalarc.scss 13:1  root stylesheet
2024-03-04 16:11:17.772 [error] 编译错误 Can't find stylesheet to import.
   ╷
13 │ @use "base";
   │ ^^^^^^^^^^^
   ╵
  c:\Users\utente\AppData\Local\Vivaldi\Mods\VivalArc-main\css\vivaldi-vh-vivalarc.scss 13:1  root stylesheet
```

The chinese characters mean "Compilation error", I guess it's a missing translation from the extension.

**Comment by HKayn** [comment]
Hi! You don't actually need to compile the CSS file yourself. I provide precompiled CSS files for both editions of Vivaldi VH on the Releases page of this repository: https://github.com/HKayn/vivaldi-vh/releases/latest

**Comment by DavidBevi** [comment]
Seems like I need a crash course for GitHub then 😅 thanks :)
