### ISSUE TITLE
Missing Trashcan and Synced Tabs

### ISSUE THREAD

**Issue by scifiscorpio420** [HKayn/vivaldi-vh#8]
I'm really enjoying your browser mod.  Thank you for the hard work. I do have one request, is it possible to enable the Trashcan and/or Synced Tabs button in the pillar?  Being able to quickly open tabs from my phone in the desktop is one of the core reasons I use Vivaldi. It looks like this was present in previous versions but not the current version. Either way thank you again for making this.

**Comment by H4M5TER** [comment]
actually I'm using latest 1.4.1 with cloud and trashcan available

**Comment by scifiscorpio420** [comment]
Thank you for the response. I was using this with VivalArc and their css was disabling those icons. I found the offending line and removed it. Thanks again for making such a cool Vivaldi theme.
