### ISSUE TITLE
feature: pin items in the tabbar

### ISSUE THREAD

**Issue by H4M5TER** [HKayn/vivaldi-vh#9]
I hope scrolling won't make pinned tabs ~and new page~ button disappear

Edit: After updating to the latest version, I found the new page button didn't scroll with tabs anymore.

**Comment by HKayn** [comment]
Hi, sorry for the super late reply!

At the moment I'd consider this feature request to be out of scope for Vivaldi VH. My mod leaves the contents of the tab bar untouched, so there shouldn't be any compatibility issues with other CSS mods that add this feature.
